## Assignment Data Science Masters (26-FEB-2023) : 
## aradhyad73@gmail.com
## 

Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Data type difference between list_ and array_list
python
Answer 1: 

In [2]:

import numpy as np

list_ = ['1', '2', '3', '4', '5']

# Convert list to numpy array
array_list = np.array(object=list_)

# Print data types
print("Data type of list_: ", type(list_[0]))
print("Data type of array_list: ", array_list.dtype)

Data type of list_:  <class 'str'>
Data type of array_list:  <U1


Q2. Data type of each element in list_ and array_list
Answer:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

# Convert list to numpy array with dtype=int
array_list = np.array(object=list_, dtype=int)

# Print data types of each element
print("Data types of elements in list_: ", [type(item) for item in list_])
print("Data types of elements in array_list: ", array_list.dtype)


Data types of elements in list_:  [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
Data types of elements in array_list:  int64


Q3. Data type difference after explicitly setting dtype=int
Answer:

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

# Convert list to numpy array with dtype=int
array_list = np.array(object=list_, dtype=int)

# Print data types of each element
print("Data types of elements in list_: ", [type(item) for item in list_])
print("Data types of elements in array_list: ", array_list.dtype)


Data types of elements in list_:  [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
Data types of elements in array_list:  int64


Q4. Characteristics of num_array
Answer :

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]

num_array = np.array(object=num_list)

# Shape of num_array
print("Shape of num_array: ", num_array.shape)

# Size of num_array
print("Size of num_array: ", num_array.size)


Shape of num_array:  (2, 3)
Size of num_array:  6


Q5. Create a numpy array of zeros with shape (3,3)
answer :

In [6]:
import numpy as np

zeros_array = np.zeros((3, 3))
print("Zeros array of shape (3,3):\n", zeros_array)


Zeros array of shape (3,3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5)
Answer:

In [7]:
import numpy as np

identity_matrix = np.eye(5)
print("Identity matrix of shape (5,5):\n", identity_matrix)


Identity matrix of shape (5,5):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
